sudo: required
services:
        - docker
before_install:
        - docker build -t houssem/docker-react -f Dockerfile.dev .
script:
        - docker run -e CI=true houssem/docker-react npm run test -- --coverage
